import {
  Bike,
  BookOpen,
  Bot,
  Brain,
  Calculator,
  Camera,
  Clapperboard,
  Code,
  Coffee,
  Cpu,
  Dice5,
  Drama,
  Dumbbell,
  Feather,
  FlaskConical,
  Flame,
  Footprints,
  Gamepad2,
  Globe,
  GraduationCap,
  Guitar,
  Headphones,
  HeartHandshake,
  Languages,
  Leaf,
  Lightbulb,
  Medal,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Palette,
  PartyPopper,
  PenTool,
  Pizza,
  Plane,
  Puzzle,
  Rocket,
  Satellite,
  Sparkles,
  Target,
  Telescope,
  Terminal,
  Trophy,
  Users,
  Volleyball,
  Waves,
} from 'lucide-react';

// Kulüp simgeleri: işletim sistemine göre farklı görünen emojiler yerine
// uygulamanın ikon setinden çizgi ikonlar. Veritabanında "icon:<anahtar>"
// olarak saklanır; eski emoji değerleri de görüntülenmeye devam eder.
export const CLUB_ICONS = {
  cpu: Cpu,
  code: Code,
  terminal: Terminal,
  bot: Bot,
  gamepad: Gamepad2,
  rocket: Rocket,
  satellite: Satellite,
  brain: Brain,
  trophy: Trophy,
  dumbbell: Dumbbell,
  bike: Bike,
  mountain: Mountain,
  volleyball: Volleyball,
  footprints: Footprints,
  waves: Waves,
  medal: Medal,
  palette: Palette,
  camera: Camera,
  music: Music,
  guitar: Guitar,
  film: Clapperboard,
  pen: PenTool,
  drama: Drama,
  headphones: Headphones,
  book: BookOpen,
  flask: FlaskConical,
  calculator: Calculator,
  globe: Globe,
  lightbulb: Lightbulb,
  microscope: Microscope,
  languages: Languages,
  graduation: GraduationCap,
  coffee: Coffee,
  mic: Mic,
  pizza: Pizza,
  dice: Dice5,
  leaf: Leaf,
  heart: HeartHandshake,
  party: PartyPopper,
  users: Users,
  sparkles: Sparkles,
  target: Target,
  puzzle: Puzzle,
  moon: Moon,
  flame: Flame,
  plane: Plane,
  telescope: Telescope,
  feather: Feather,
};

// Kategori renkleri ve her kategori için önerilen simgeler
export const CLUB_CATEGORY_STYLE = {
  Teknoloji: { tone: '#6f8db3', icons: ['cpu', 'code', 'bot', 'gamepad', 'rocket', 'terminal', 'satellite', 'brain'] },
  Spor: { tone: '#7fa88a', icons: ['trophy', 'dumbbell', 'volleyball', 'bike', 'mountain', 'footprints', 'waves', 'medal'] },
  Sanat: { tone: '#d97757', icons: ['palette', 'camera', 'music', 'guitar', 'film', 'drama', 'pen', 'headphones'] },
  Akademik: { tone: '#c9a24a', icons: ['book', 'flask', 'microscope', 'calculator', 'lightbulb', 'globe', 'languages', 'graduation'] },
  Sosyal: { tone: '#b08968', icons: ['coffee', 'mic', 'pizza', 'dice', 'party', 'heart', 'leaf', 'users'] },
  Diğer: { tone: '#8e8499', icons: ['sparkles', 'target', 'puzzle', 'telescope', 'moon', 'flame', 'plane', 'feather'] },
};

export const ICON_PREFIX = 'icon:';

export function toneForCategory(category) {
  return (CLUB_CATEGORY_STYLE[category] || CLUB_CATEGORY_STYLE.Sosyal).tone;
}
