// Veritabanına başlangıç üniversite listesini ekler.
// Devlet ve vakıf üniversitelerinin kapsamlı listesi (YÖK verilerine dayanır).
// Not: emailDomain alanları otomatik doğrulama için kullanılır. Bir üniversitenin
// gerçek öğrenci e-posta domaini burada yanlış/eksikse, kayıt sırasında öğrenci
// belgesi yükleyerek manuel doğrulama akışı devreye girer — kayıt engellenmez.
// Çalıştırmak için: node prisma/seed.js

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const universities = [
  // ---------------- Devlet Üniversiteleri ----------------
  { name: 'Abdullah Gül Üniversitesi', emailDomain: 'agu.edu.tr' },
  { name: 'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', emailDomain: 'atu.edu.tr' },
  { name: 'Adıyaman Üniversitesi', emailDomain: 'adiyaman.edu.tr' },
  { name: 'Afyon Kocatepe Üniversitesi', emailDomain: 'aku.edu.tr' },
  { name: 'Afyonkarahisar Sağlık Bilimleri Üniversitesi', emailDomain: 'afsu.edu.tr' },
  { name: 'Akdeniz Üniversitesi', emailDomain: 'akdeniz.edu.tr' },
  { name: 'Aksaray Üniversitesi', emailDomain: 'aksaray.edu.tr' },
  { name: 'Alanya Alaaddin Keykubat Üniversitesi', emailDomain: 'alanya.edu.tr' },
  { name: 'Amasya Üniversitesi', emailDomain: 'amasya.edu.tr' },
  { name: 'Anadolu Üniversitesi', emailDomain: 'anadolu.edu.tr' },
  { name: 'Ankara Hacı Bayram Veli Üniversitesi', emailDomain: 'hacibayram.edu.tr' },
  { name: 'Ankara Müzik ve Güzel Sanatlar Üniversitesi', emailDomain: 'mgu.edu.tr' },
  { name: 'Ankara Sosyal Bilimler Üniversitesi', emailDomain: 'asbu.edu.tr' },
  { name: 'Ankara Yıldırım Beyazıt Üniversitesi', emailDomain: 'aybu.edu.tr' },
  { name: 'Ankara Üniversitesi', emailDomain: 'ankara.edu.tr' },
  { name: 'Ardahan Üniversitesi', emailDomain: 'ardahan.edu.tr' },
  { name: 'Artvin Çoruh Üniversitesi', emailDomain: 'artvin.edu.tr' },
  { name: 'Atatürk Üniversitesi', emailDomain: 'atauni.edu.tr' },
  { name: 'Aydın Adnan Menderes Üniversitesi', emailDomain: 'adu.edu.tr' },
  { name: 'Ağrı İbrahim Çeçen Üniversitesi', emailDomain: 'agri.edu.tr' },
  { name: 'Balıkesir Üniversitesi', emailDomain: 'balikesir.edu.tr' },
  { name: 'Bandırma Onyedi Eylül Üniversitesi', emailDomain: 'bandirma.edu.tr' },
  { name: 'Bartın Üniversitesi', emailDomain: 'bartin.edu.tr' },
  { name: 'Batman Üniversitesi', emailDomain: 'batman.edu.tr' },
  { name: 'Bayburt Üniversitesi', emailDomain: 'bayburt.edu.tr' },
  { name: 'Bilecik Şeyh Edebali Üniversitesi', emailDomain: 'bilecik.edu.tr' },
  { name: 'Bingöl Üniversitesi', emailDomain: 'bingol.edu.tr' },
  { name: 'Bitlis Eren Üniversitesi', emailDomain: 'beu.edu.tr' },
  { name: 'Bolu Abant İzzet Baysal Üniversitesi', emailDomain: 'ibu.edu.tr' },
  { name: 'Boğaziçi Üniversitesi', emailDomain: 'boun.edu.tr' },
  { name: 'Burdur Mehmet Akif Ersoy Üniversitesi', emailDomain: 'mehmetakif.edu.tr' },
  { name: 'Bursa Teknik Üniversitesi', emailDomain: 'btu.edu.tr' },
  { name: 'Bursa Uludağ Üniversitesi', emailDomain: 'uludag.edu.tr' },
  { name: 'Dicle Üniversitesi', emailDomain: 'dicle.edu.tr' },
  { name: 'Dokuz Eylül Üniversitesi', emailDomain: 'deu.edu.tr' },
  { name: 'Düzce Üniversitesi', emailDomain: 'duzce.edu.tr' },
  { name: 'Ege Üniversitesi', emailDomain: 'ege.edu.tr' },
  { name: 'Erciyes Üniversitesi', emailDomain: 'erciyes.edu.tr' },
  { name: 'Erzincan Binali Yıldırım Üniversitesi', emailDomain: 'erzincan.edu.tr' },
  { name: 'Erzurum Teknik Üniversitesi', emailDomain: 'erzurum.edu.tr' },
  { name: 'Eskişehir Osmangazi Üniversitesi', emailDomain: 'ogu.edu.tr' },
  { name: 'Eskişehir Teknik Üniversitesi', emailDomain: 'eskisehir.edu.tr' },
  { name: 'Fırat Üniversitesi', emailDomain: 'firat.edu.tr' },
  { name: 'Galatasaray Üniversitesi', emailDomain: 'gsu.edu.tr' },
  { name: 'Gazi Üniversitesi', emailDomain: 'gazi.edu.tr' },
  { name: 'Gaziantep Üniversitesi', emailDomain: 'gantep.edu.tr' },
  { name: 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi', emailDomain: 'gibtu.edu.tr' },
  { name: 'Gebze Teknik Üniversitesi', emailDomain: 'gtu.edu.tr' },
  { name: 'Giresun Üniversitesi', emailDomain: 'giresun.edu.tr' },
  { name: 'Gümüşhane Üniversitesi', emailDomain: 'gumushane.edu.tr' },
  { name: 'Hacettepe Üniversitesi', emailDomain: 'hacettepe.edu.tr' },
  { name: 'Hakkari Üniversitesi', emailDomain: 'hakkari.edu.tr' },
  { name: 'Harran Üniversitesi', emailDomain: 'harran.edu.tr' },
  { name: 'Hatay Mustafa Kemal Üniversitesi', emailDomain: 'mku.edu.tr' },
  { name: 'Hitit Üniversitesi', emailDomain: 'hitit.edu.tr' },
  { name: 'Isparta Uygulamalı Bilimler Üniversitesi', emailDomain: 'isparta.edu.tr' },
  { name: 'Iğdır Üniversitesi', emailDomain: 'igdir.edu.tr' },
  { name: 'Kafkas Üniversitesi', emailDomain: 'kafkas.edu.tr' },
  { name: 'Kahramanmaraş Sütçü İmam Üniversitesi', emailDomain: 'ksu.edu.tr' },
  { name: 'Kahramanmaraş İstiklal Üniversitesi', emailDomain: 'istiklal.edu.tr' },
  { name: 'Karabük Üniversitesi', emailDomain: 'karabuk.edu.tr' },
  { name: 'Karadeniz Teknik Üniversitesi', emailDomain: 'ktu.edu.tr' },
  { name: 'Karamanoğlu Mehmetbey Üniversitesi', emailDomain: 'kmu.edu.tr' },
  { name: 'Kastamonu Üniversitesi', emailDomain: 'kastamonu.edu.tr' },
  { name: 'Kayseri Üniversitesi', emailDomain: 'kayseri.edu.tr' },
  { name: 'Kilis 7 Aralık Üniversitesi', emailDomain: 'kilis.edu.tr' },
  { name: 'Kocaeli Üniversitesi', emailDomain: 'kocaeli.edu.tr' },
  { name: 'Konya Teknik Üniversitesi', emailDomain: 'ktun.edu.tr' },
  { name: 'Kütahya Dumlupınar Üniversitesi', emailDomain: 'dpu.edu.tr' },
  { name: 'Kütahya Sağlık Bilimleri Üniversitesi', emailDomain: 'ksbu.edu.tr' },
  { name: 'Kırklareli Üniversitesi', emailDomain: 'klu.edu.tr' },
  { name: 'Kırıkkale Üniversitesi', emailDomain: 'kku.edu.tr' },
  { name: 'Kırşehir Ahi Evran Üniversitesi', emailDomain: 'ahievran.edu.tr' },
  { name: 'Malatya Turgut Özal Üniversitesi', emailDomain: 'ozal.edu.tr' },
  { name: 'Manisa Celâl Bayar Üniversitesi', emailDomain: 'cbu.edu.tr' },
  { name: 'Mardin Artuklu Üniversitesi', emailDomain: 'artuklu.edu.tr' },
  { name: 'Marmara Üniversitesi', emailDomain: 'marmara.edu.tr' },
  { name: 'Mersin Üniversitesi', emailDomain: 'mersin.edu.tr' },
  { name: 'Mimar Sinan Güzel Sanatlar Üniversitesi', emailDomain: 'msgsu.edu.tr' },
  { name: 'Munzur Üniversitesi', emailDomain: 'munzur.edu.tr' },
  { name: 'Muğla Sıtkı Koçman Üniversitesi', emailDomain: 'mu.edu.tr' },
  { name: 'Muş Alparslan Üniversitesi', emailDomain: 'alparslan.edu.tr' },
  { name: 'Necmettin Erbakan Üniversitesi', emailDomain: 'erbakan.edu.tr' },
  { name: 'Nevşehir Hacı Bektaş Veli Üniversitesi', emailDomain: 'nevsehir.edu.tr' },
  { name: 'Niğde Ömer Halisdemir Üniversitesi', emailDomain: 'ohu.edu.tr' },
  { name: 'Ondokuz Mayıs Üniversitesi', emailDomain: 'omu.edu.tr' },
  { name: 'Ordu Üniversitesi', emailDomain: 'odu.edu.tr' },
  { name: 'Orta Doğu Teknik Üniversitesi', emailDomain: 'metu.edu.tr' },
  { name: 'Osmaniye Korkut Ata Üniversitesi', emailDomain: 'osmaniye.edu.tr' },
  { name: 'Pamukkale Üniversitesi', emailDomain: 'pau.edu.tr' },
  { name: 'Recep Tayyip Erdoğan Üniversitesi', emailDomain: 'erdogan.edu.tr' },
  { name: 'Sakarya Uygulamalı Bilimler Üniversitesi', emailDomain: 'subu.edu.tr' },
  { name: 'Sakarya Üniversitesi', emailDomain: 'sakarya.edu.tr' },
  { name: 'Samsun Üniversitesi', emailDomain: 'samsun.edu.tr' },
  { name: 'Sağlık Bilimleri Üniversitesi', emailDomain: 'sbu.edu.tr' },
  { name: 'Selçuk Üniversitesi', emailDomain: 'selcuk.edu.tr' },
  { name: 'Siirt Üniversitesi', emailDomain: 'siirt.edu.tr' },
  { name: 'Sinop Üniversitesi', emailDomain: 'sinop.edu.tr' },
  { name: 'Sivas Bilim ve Teknoloji Üniversitesi', emailDomain: 'sivas.edu.tr' },
  { name: 'Sivas Cumhuriyet Üniversitesi', emailDomain: 'cumhuriyet.edu.tr' },
  { name: 'Süleyman Demirel Üniversitesi', emailDomain: 'sdu.edu.tr' },
  { name: 'Tarsus Üniversitesi', emailDomain: 'tarsus.edu.tr' },
  { name: 'Tekirdağ Namık Kemal Üniversitesi', emailDomain: 'nku.edu.tr' },
  { name: 'Tokat Gaziosmanpaşa Üniversitesi', emailDomain: 'gop.edu.tr' },
  { name: 'Trabzon Üniversitesi', emailDomain: 'trabzon.edu.tr' },
  { name: 'Trakya Üniversitesi', emailDomain: 'trakya.edu.tr' },
  { name: 'Türk-alman Üniversitesi', emailDomain: 'tau.edu.tr' },
  { name: 'Uşak Üniversitesi', emailDomain: 'usak.edu.tr' },
  { name: 'Van Yüzüncü Yıl Üniversitesi', emailDomain: 'yyu.edu.tr' },
  { name: 'Yalova Üniversitesi', emailDomain: 'yalova.edu.tr' },
  { name: 'Yozgat Bozok Üniversitesi', emailDomain: 'bozok.edu.tr' },
  { name: 'Yıldız Teknik Üniversitesi', emailDomain: 'yildiz.edu.tr' },
  { name: 'Zonguldak Bülent Ecevit Üniversitesi', emailDomain: 'beun.edu.tr' },
  { name: 'Çanakkale Onsekiz Mart Üniversitesi', emailDomain: 'comu.edu.tr' },
  { name: 'Çankırı Karatekin Üniversitesi', emailDomain: 'karatekin.edu.tr' },
  { name: 'Çukurova Üniversitesi', emailDomain: 'cu.edu.tr' },
  { name: 'İnönü Üniversitesi', emailDomain: 'inonu.edu.tr' },
  { name: 'İskenderun Teknik Üniversitesi', emailDomain: 'iste.edu.tr' },
  { name: 'İstanbul Medeniyet Üniversitesi', emailDomain: 'medeniyet.edu.tr' },
  { name: 'İstanbul Teknik Üniversitesi', emailDomain: 'itu.edu.tr' },
  { name: 'İstanbul Üniversitesi', emailDomain: 'istanbul.edu.tr' },
  { name: 'İstanbul Üniversitesi-Cerrahpaşa', emailDomain: 'iuc.edu.tr' },
  { name: 'İzmir Bakırçay Üniversitesi', emailDomain: 'bakircay.edu.tr' },
  { name: 'İzmir Demokrasi Üniversitesi', emailDomain: 'idu.edu.tr' },
  { name: 'İzmir Katip Çelebi Üniversitesi', emailDomain: 'ikc.edu.tr' },
  { name: 'İzmir Yüksek Teknoloji Enstitüsü', emailDomain: 'iyte.edu.tr' },
  { name: 'Şırnak Üniversitesi', emailDomain: 'sirnak.edu.tr' },

  // ---------------- Vakıf Üniversiteleri ----------------
  { name: 'Acıbadem Mehmet Ali Aydınlar Üniversitesi', emailDomain: 'acibadem.edu.tr' },
  { name: 'Alanya Üniversitesi', emailDomain: 'alanyauniversity.edu.tr' },
  { name: 'Altınbaş Üniversitesi', emailDomain: 'altinbas.edu.tr' },
  { name: 'Ankara Bilim Üniversitesi', emailDomain: 'ankarabilim.edu.tr' },
  { name: 'Ankara Medipol Üniversitesi', emailDomain: 'ankaramedipol.edu.tr' },
  { name: 'Antalya Belek Üniversitesi', emailDomain: 'belek.edu.tr' },
  { name: 'Antalya Bilim Üniversitesi', emailDomain: 'antalya.edu.tr' },
  { name: 'Ataşehir Adıgüzel Meslek Yüksekokulu', emailDomain: 'adiguzel.edu.tr' },
  { name: 'Atılım Üniversitesi', emailDomain: 'atilim.edu.tr' },
  { name: 'Avrasya Üniversitesi', emailDomain: 'avrasya.edu.tr' },
  { name: 'Bahçeşehir Üniversitesi', emailDomain: 'bahcesehir.edu.tr' },
  { name: 'Başkent Üniversitesi', emailDomain: 'baskent.edu.tr' },
  { name: 'Beykoz Üniversitesi', emailDomain: 'beykoz.edu.tr' },
  { name: 'Bezm-i Âlem Vakıf Üniversitesi', emailDomain: 'bezmialem.edu.tr' },
  { name: 'Biruni Üniversitesi', emailDomain: 'biruni.edu.tr' },
  { name: 'Demiroğlu Bilim Üniversitesi', emailDomain: 'demiroglu.bilim.edu.tr' },
  { name: 'Doğuş Üniversitesi', emailDomain: 'dogus.edu.tr' },
  { name: 'Fatih Sultan Mehmet Vakıf Üniversitesi', emailDomain: 'fsm.edu.tr' },
  { name: 'Fenerbahçe Üniversitesi', emailDomain: 'fbu.edu.tr' },
  { name: 'Haliç Üniversitesi', emailDomain: 'halic.edu.tr' },
  { name: 'Hasan Kalyoncu Üniversitesi', emailDomain: 'hku.edu.tr' },
  { name: 'Işık Üniversitesi', emailDomain: 'isikun.edu.tr' },
  { name: 'KTO Karatay Üniversitesi', emailDomain: 'karatay.edu.tr' },
  { name: 'Kadir Has Üniversitesi', emailDomain: 'khas.edu.tr' },
  { name: 'Kapadokya Üniversitesi', emailDomain: 'kapadokya.edu.tr' },
  { name: 'Kocaeli Sağlık ve Teknoloji Üniversitesi', emailDomain: 'kocaelisaglik.edu.tr' },
  { name: 'Konya Gıda ve Tarım Üniversitesi', emailDomain: 'gidatarim.edu.tr' },
  { name: 'Koç Üniversitesi', emailDomain: 'ku.edu.tr' },
  { name: 'Lokman Hekim Üniversitesi', emailDomain: 'lokmanhekim.edu.tr' },
  { name: 'MEF Üniversitesi', emailDomain: 'mef.edu.tr' },
  { name: 'Maltepe Üniversitesi', emailDomain: 'maltepe.edu.tr' },
  { name: 'Mudanya Üniversitesi', emailDomain: 'mudanya.edu.tr' },
  { name: 'Nuh Naci Yazgan Üniversitesi', emailDomain: 'nny.edu.tr' },
  { name: 'OSTİM Teknik Üniversitesi', emailDomain: 'ostimteknik.edu.tr' },
  { name: 'Piri Reis Üniversitesi', emailDomain: 'pirireis.edu.tr' },
  { name: 'SANKO Üniversitesi', emailDomain: 'sanko.edu.tr' },
  { name: 'Sabancı Üniversitesi', emailDomain: 'sabanciuniv.edu' },
  { name: 'TED Üniversitesi', emailDomain: 'tedu.edu.tr' },
  { name: 'TOBB Ekonomi ve Teknoloji Üniversitesi', emailDomain: 'etu.edu.tr' },
  { name: 'Toros Üniversitesi', emailDomain: 'toros.edu.tr' },
  { name: 'Türk Hava Kurumu Üniversitesi', emailDomain: 'thk.edu.tr' },
  { name: 'Ufuk Üniversitesi', emailDomain: 'ufuk.edu.tr' },
  { name: 'Yaşar Üniversitesi', emailDomain: 'yasar.edu.tr' },
  { name: 'Yeditepe Üniversitesi', emailDomain: 'yeditepe.edu.tr' },
  { name: 'Yüksek İhtisas Üniversitesi', emailDomain: 'yiu.edu.tr' },
  { name: 'Çankaya Üniversitesi', emailDomain: 'cankaya.edu.tr' },
  { name: 'Çağ Üniversitesi', emailDomain: 'cag.edu.tr' },
  { name: 'Özyeğin Üniversitesi', emailDomain: 'ozyegin.edu.tr' },
  { name: 'Üsküdar Üniversitesi', emailDomain: 'uskudar.edu.tr' },
  { name: 'İbn Haldun Üniversitesi', emailDomain: 'ihu.edu.tr' },
  { name: 'İhsan Doğramacı Bilkent Üniversitesi', emailDomain: 'bilkent.edu.tr' },
  { name: 'İstanbul 29 Mayıs Üniversitesi', emailDomain: '29mayis.edu.tr' },
  { name: 'İstanbul Arel Üniversitesi', emailDomain: 'arel.edu.tr' },
  { name: 'İstanbul Atlas Üniversitesi', emailDomain: 'atlas.edu.tr' },
  { name: 'İstanbul Aydın Üniversitesi', emailDomain: 'aydin.edu.tr' },
  { name: 'İstanbul Beykent Üniversitesi', emailDomain: 'beykent.edu.tr' },
  { name: 'İstanbul Bilgi Üniversitesi', emailDomain: 'bilgi.edu.tr' },
  { name: 'İstanbul Esenyurt Üniversitesi', emailDomain: 'esenyurt.edu.tr' },
  { name: 'İstanbul Galata Üniversitesi', emailDomain: 'galata.edu.tr' },
  { name: 'İstanbul Gedik Üniversitesi', emailDomain: 'gedik.edu.tr' },
  { name: 'İstanbul Gelişim Üniversitesi', emailDomain: 'gelisim.edu.tr' },
  { name: 'İstanbul Kent Üniversitesi', emailDomain: 'kent.edu.tr' },
  { name: 'İstanbul Kültür Üniversitesi', emailDomain: 'iku.edu.tr' },
  { name: 'İstanbul Medipol Üniversitesi', emailDomain: 'medipol.edu.tr' },
  { name: 'İstanbul Nişantaşı Üniversitesi', emailDomain: 'nisantasi.edu.tr' },
  { name: 'İstanbul Okan Üniversitesi', emailDomain: 'okan.edu.tr' },
  { name: 'İstanbul Rumeli Üniversitesi', emailDomain: 'rumeli.edu.tr' },
  { name: 'İstanbul Sabahattin Zaim Üniversitesi', emailDomain: 'izu.edu.tr' },
  { name: 'İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu', emailDomain: 'issb.edu.tr' },
  { name: 'İstanbul Sağlık ve Teknoloji Üniversitesi', emailDomain: 'istun.edu.tr' },
  { name: 'İstanbul Ticaret Üniversitesi', emailDomain: 'ticaret.edu.tr' },
  { name: 'İstanbul Topkapı Üniversitesi', emailDomain: 'topkapi.edu.tr' },
  { name: 'İstanbul Yeni Yüzyıl Üniversitesi', emailDomain: 'yeniyuzyil.edu.tr' },
  { name: 'İstanbul Şişli Meslek Yüksekokulu', emailDomain: 'sisli.edu.tr' },
  { name: 'İstinye Üniversitesi', emailDomain: 'istinye.edu.tr' },
  { name: 'İzmir Ekonomi Üniversitesi', emailDomain: 'ieu.edu.tr' },
  { name: 'İzmir Kavram Meslek Yüksekokulu', emailDomain: 'kavram.edu.tr' },
  { name: 'İzmir Tınaztepe Üniversitesi', emailDomain: 'tinaztepe.edu.tr' },
];

async function main() {
  for (const uni of universities) {
    await prisma.university.upsert({
      where: { name: uni.name },
      update: { emailDomain: uni.emailDomain },
      create: uni,
    });
  }
  console.log(`${universities.length} üniversite eklendi/güncellendi.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
